export const projectList = [
  {
    id: 0,
    title: 'sechan',
    description: '프론트엔드 김세찬입니다.',
  },
  {
    id: 1,
    title: 'hanwha-motiev',
    description: '한화모티브',
    description02: '기존 전기차 충전 한화모티브 앱 리뉴얼',
    project: {
      projectTitle: 'Hanwha-motiev',
      projectStack01: 'React-native',
      projectStack02: 'Typescript',
      projectStack03: 'Styled-component',
      projectStack04: 'Recoil',
      projectStack05: 'React-query',
      mainImg01: '',
      mainImg02: '',
      projectConceptDesc01:
        '한화모티브에서 기존에 운영중이던 전기차 충전소 찾기 및 충전 앱 리뉴얼 프로젝트',
      projectConceptImg01: '',
      projectConceptDesc02:
        '전국의 전기차 충전소를 대상으로 현위치 기준 주변 충전소 및 추천 충전소 노출하여 전기차 충전을 용이하게 할 수 있게 도와주는 서비스입니다.',
      projectConceptImg02: '',
      projectProgressDesc01:
        '현 위치를 기반으로 주변 충전소를 볼 수 있습니다. naver map api와 webview를 이용하여 개발하였으며, 즐겨찾는 충전소 / 검색도 가능합니다. 지도 내의 충전소의 경우 전체 충전기 갯수와 현재 사용가능 / 사용중 / 설치예정 / 사용불가의 상태를 핀의 색상으로 보여주어 충전소의 상태를 한눈에 확인 가능하여 전기차주의 불편함을 덜어주었습니다. 또한 지도 축소 시 충전소 여러개가 겹쳐보일 경우 clustering 기능을 사용하여 지역 내 충전소 갯수와 충전소의 현재 상태를 확인할 수 있습니다.',
      projectProgressDescTitle01: 'MAP',
      projectProgressImg01: '',
      projectProgressDesc02:
        '현 위치를 기반으로 주변 충전소를 확인한 후 충전소 터치 시 충전소의 상태와 바로 예약할 수 있는 찜하기 기능이 있습니다. 지도뿐만 아니라 시간 기반으로 예약을 하고 싶은 전기차주를 위하여 먼저 원하는 시간을 선택하면 그 시간에 맞는 충전소만 보여지게 되며 그 중에 원하는 충전소를 먼저 찜할 수 있습니다.',
      projectProgressDescTitle02: 'RESERVATION',
      projectProgressImg02: '',
      projectProgressDesc03:
        '실시간으로 충전현황도 확인 가능하며, 충전을 완료하고 난 뒤 나중에 충전내역을 확인할 수 있습니다. 결제 방식 즉, 포인트를 이용하였는지, 쿠폰을 이용하였는지, 다양한 결제 수단 중 어떤 수단으로 결제하였는지 바로 확인할 수 있습니다.',
      projectProgressDescTitle03: 'CHARGING STATUS',
      projectProgressImg03: '',
      projectProgressDesc04:
        '충전을 할 때마다 데이터가 점점 쌓여, 내가 선호하는 충전방식 및 자주 방문한 충전소 등의 내용을 차트를 통하여 확인할 수 있는 소소한 재미도 있습니다.',
      projectProgressDescTitle04: 'CHARGING HISTORY',
      projectProgressImg04: '',
    },
  },
  {
    id: 2,
    title: 'pantos',
    description: '판토스입니다.',
    description02: '운송사 / 화주 / 관리자 어드민 웹 개발',
    project: {
      projectTitle: 'Pantos',
      projectStack01: 'Jquery',
      projectStack02: 'Javascript',
      projectStack03: 'css5',
      projectStack04: 'Ajax',
      mainImg01: '',
      mainImg02: '',
      projectConceptDesc01: '',
      projectConceptImg01: '',
      projectConceptDesc02: '',
      projectConceptImg02: '',
      projectProgressDesc01: '',
      projectProgressDescTitle01: '',
      projectProgressImg01: '',
      projectProgressDesc02: '',
      projectProgressDescTitle02: '',
      projectProgressImg02: '',
      projectProgressDesc03: '',
      projectProgressDescTitle03: '',
      projectProgressImg03: '',
      projectProgressDesc04: '',
      projectProgressDescTitle04: '',
      projectProgressImg04: '',
    },
  },
  {
    id: 3,
    title: 'convatec',
    description: '콘바텍입니다.',
    description02: 'PDF 뷰어 앱 개발',
    project: {
      projectTitle: 'Convatec',
      projectStack01: 'React-native',
      projectStack02: 'Javascript',
      projectStack03: 'Styled-component',
      projectStack04: 'Recoil',
      projectStack05: 'Axios',
      mainImg01: '',
      mainImg02: '',
      projectConceptDesc01: '',
      projectConceptImg01: '',
      projectConceptDesc02: '',
      projectConceptImg02: '',
      projectProgressDesc01: '',
      projectProgressDescTitle01: '',
      projectProgressImg01: '',
      projectProgressDesc02: '',
      projectProgressDescTitle02: '',
      projectProgressImg02: '',
      projectProgressDesc03: '',
      projectProgressDescTitle03: '',
      projectProgressImg03: '',
      projectProgressDesc04: '',
      projectProgressDescTitle04: '',
      projectProgressImg04: '',
    },
  },
  {
    id: 4,
    title: 'school-trip',
    description: '스쿨트립입니다.',
    description02: '교육여행 신청 및 견적 플랫폼 웹 개발',
    project: {
      projectTitle: 'School-trip',
      projectStack01: 'React',
      projectStack02: 'Typescript',
      projectStack03: 'Styled-component',
      projectStack04: 'Recoil',
      projectStack05: 'React-query',
      mainImg01: '',
      mainImg02: '',
      projectConceptDesc01: '',
      projectConceptImg01: '',
      projectConceptDesc02: '',
      projectConceptImg02: '',
      projectProgressDesc01: '',
      projectProgressDescTitle01: '',
      projectProgressImg01: '',
      projectProgressDesc02: '',
      projectProgressDescTitle02: '',
      projectProgressImg02: '',
      projectProgressDesc03: '',
      projectProgressDescTitle03: '',
      projectProgressImg03: '',
      projectProgressDesc04: '',
      projectProgressDescTitle04: '',
      projectProgressImg04: '',
    },
  },
  {
    id: 5,
    title: 'hubbing',
    description: '허빙입니다.',
    description02: '아르바이트 / 사장님 알바 및 급여관리 앱 개발',
    project: {
      projectTitle: 'Hubbing',
      projectStack01: 'React-native',
      projectStack02: 'Typescript',
      projectStack03: 'Styled-component',
      projectStack04: 'Recoil',
      projectStack05: 'Axios',
      mainImg01: '',
      mainImg02: '',
      projectConceptDesc01: '',
      projectConceptImg01: '',
      projectConceptDesc02: '',
      projectConceptImg02: '',
      projectProgressDesc01: '',
      projectProgressDescTitle01: '',
      projectProgressImg01: '',
      projectProgressDesc02: '',
      projectProgressDescTitle02: '',
      projectProgressImg02: '',
      projectProgressDesc03: '',
      projectProgressDescTitle03: '',
      projectProgressImg03: '',
      projectProgressDesc04: '',
      projectProgressDescTitle04: '',
      projectProgressImg04: '',
    },
  },
  {
    id: 6,
    title: 'alba-edu',
    description: '알바에듀입니다.',
    description02: '학생,학부모 / 선생 과외 매칭 플랫폼 웹 개발',
    project: {
      projectTitle: 'Alba-edu',
      projectStack01: 'React',
      projectStack02: 'Javascript',
      projectStack03: 'Styled-component',
      projectStack04: 'Recoil',
      projectStack05: 'Axios',
      mainImg01: '',
      mainImg02: '',
      projectConceptDesc01: '',
      projectConceptImg01: '',
      projectConceptDesc02: '',
      projectConceptImg02: '',
      projectProgressDesc01: '',
      projectProgressDescTitle01: '',
      projectProgressImg01: '',
      projectProgressDesc02: '',
      projectProgressDescTitle02: '',
      projectProgressImg02: '',
      projectProgressDesc03: '',
      projectProgressDescTitle03: '',
      projectProgressImg03: '',
      projectProgressDesc04: '',
      projectProgressDescTitle04: '',
      projectProgressImg04: '',
    },
  },
];
